// Code generated by MCHP Chatbot

import { create } from 'zustand';
import axios from 'axios';

const API_URL = process.env.EXPO_PUBLIC_BACKEND_URL;

// --- Added interfaces from the suggested edit ---
export interface StockItem {
  id: string;
  barcode?: string;
  name: string;
  brand?: string;
  image_url?: string;
  category?: string;
  quantity?: string;
  expiry_date?: string;
  added_date: string;
  status: string;
  notes?: string;
}

export interface Stats {
  total_items: number;
  expiring_soon: number;
  expired: number;
  consumed_this_week: number;
  thrown_this_week: number;
}

// --- Main StockStore Interface and Zustand Implementation ---

interface StockStore {
  items: StockItem[];
  priorityItems: StockItem[];
  stats: Stats;
  isLoading: boolean;
  error: string | null;

  fetchStock: () => Promise<void>;
  fetchPriorityItems: () => Promise<void>;
  fetchStats: () => Promise<void>;
  markConsumed: (itemId: string) => Promise<void>;
  markThrown: (itemId: string) => Promise<void>;
  lookupProduct: (barcode: string) => Promise<any>;
  addItem: (item: Partial<StockItem>) => Promise<StockItem | null>;
}

export const useStockStore = create<StockStore>((set) => ({
  items: [],
  priorityItems: [],
  stats: {
    total_items: 0,
    expiring_soon: 0,
    expired: 0,
    consumed_this_week: 0,
    thrown_this_week: 0,
  },
  isLoading: false,
  error: null,

  fetchStock: async () => {
    try {
      const res = await axios.get(`${API_URL}/api/stock?status=active`);

      set({ items: res.data });
    } catch (err: any) {
      set({ error: err.message });

    }
  },

  fetchPriorityItems: async () => {
    try {
      const res = await axios.get(`${API_URL}/api/stock/priority`);
      set({ priorityItems: res.data });
    } catch (err: any) {
      set({ error: err.message });
    }
  },

  fetchStats: async () => {
    try {
      const res = await axios.get(`${API_URL}/api/stats`);
      set({ stats: res.data });
    } catch (err: any) {
      set({ error: err.message });
    }
  },

  markConsumed: async (itemId: string) => {
    try {
      await axios.post(`${API_URL}/api/stock/${itemId}/consume`);
      await useStockStore.getState().fetchStock();
    } catch (err: any) {
      set({ error: err.message });

    }
  },

  markThrown: async (itemId: string) => {
    try {
      await axios.post(`${API_URL}/api/stock/${itemId}/throw`);
      await useStockStore.getState().fetchStock();
    } catch (err: any) {
      set({ error: err.message });

    }
  },

  lookupProduct: async (barcode: string) => {
    try {
      const res = await axios.get(`${API_URL}/api/product/${barcode}`);
      return res.data;
    } catch (err: any) {

      return null;
    }
  },


  addItem: async (item) => {
    try {
      const res = await axios.post(`${API_URL}/api/stock`, item);
      await useStockStore.getState().fetchStock();
      return res.data;
    } catch (err: any) {
      console.error("Erreur lors de l'ajout :", err);
      return null;
    }
  },
}));
