#!/usr/bin/env bash
set -euo pipefail

# Generate HTML report for E2E test results
# Usage: generate-e2e-report.sh <results-dir> <output-file>

RESULTS_DIR="${1:-maestro-results}"
OUTPUT_FILE="${2:-e2e-report.html}"

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}📊 Generating E2E test report...${NC}"

# Count results
PASSED=0
FAILED=0
TOTAL=0

for dir in "$RESULTS_DIR"/*; do
  if [ ! -d "$dir" ]; then
    continue
  fi

  TOTAL=$((TOTAL + 1))
  if [ -f "$dir/status.txt" ]; then
    status=$(cat "$dir/status.txt")
    if [ "$status" = "PASSED" ]; then
      PASSED=$((PASSED + 1))
    else
      FAILED=$((FAILED + 1))
    fi
  fi
done

# Read log files
LOGCAT_CONTENT=""
if [ -f "maestro-results/logcat-full.txt" ]; then
  LOGCAT_CONTENT=$(tail -n 500 maestro-results/logcat-full.txt | sed 's/</\&lt;/g; s/>/\&gt;/g')
fi

CRASHES_CONTENT=""
if [ -f "maestro-results/rn-crashes.txt" ]; then
  CRASHES_CONTENT=$(cat maestro-results/rn-crashes.txt | sed 's/</\&lt;/g; s/>/\&gt;/g')
fi

BACKEND_LOG=""
if [ -f "backend-e2e.log" ]; then
  BACKEND_LOG=$(tail -n 200 backend-e2e.log | sed 's/</\&lt;/g; s/>/\&gt;/g')
fi

# Generate HTML
cat > "$OUTPUT_FILE" <<'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>KeepEat E2E Test Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif;
      background: #f5f5f5;
      color: #333;
      line-height: 1.6;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }
    header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 8px;
      margin-bottom: 30px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    header h1 {
      font-size: 2em;
      margin-bottom: 10px;
    }
    .summary {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 15px;
      margin-bottom: 30px;
    }
    .stat {
      background: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      text-align: center;
    }
    .stat-value {
      font-size: 2em;
      font-weight: bold;
      margin: 10px 0;
    }
    .stat-label {
      color: #666;
      font-size: 0.9em;
    }
    .passed { color: #28a745; }
    .failed { color: #dc3545; }
    .total { color: #667eea; }
    .section {
      background: white;
      padding: 20px;
      margin-bottom: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .section h2 {
      border-bottom: 2px solid #667eea;
      padding-bottom: 10px;
      margin-bottom: 15px;
      color: #333;
    }
    .log-content {
      background: #f5f5f5;
      border: 1px solid #ddd;
      border-radius: 4px;
      padding: 15px;
      font-family: "Monaco", "Menlo", "Ubuntu Mono", monospace;
      font-size: 0.85em;
      overflow-x: auto;
      max-height: 600px;
      overflow-y: auto;
      line-height: 1.4;
    }
    .error-line { color: #dc3545; }
    .warning-line { color: #ff9800; }
    .info-line { color: #2196F3; }
    .timestamp {
      color: #999;
      margin-right: 10px;
    }
    footer {
      text-align: center;
      color: #666;
      padding: 20px;
      font-size: 0.9em;
    }
    .icon {
      font-size: 2em;
      margin-bottom: 10px;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🧪 KeepEat E2E Test Report</h1>
      <p>Maestro Mobile UI Test Suite - Smoke Tests</p>
      <p style="opacity: 0.9; font-size: 0.9em; margin-top: 10px;">
        Generated: <time>TIMESTAMP_PLACEHOLDER</time>
      </p>
    </header>

    <div class="summary">
      <div class="stat">
        <div class="icon">✅</div>
        <div class="stat-label">Passed</div>
        <div class="stat-value passed">PASSED_COUNT</div>
      </div>
      <div class="stat">
        <div class="icon">❌</div>
        <div class="stat-label">Failed</div>
        <div class="stat-value failed">FAILED_COUNT</div>
      </div>
      <div class="stat">
        <div class="icon">📊</div>
        <div class="stat-label">Total</div>
        <div class="stat-value total">TOTAL_COUNT</div>
      </div>
      <div class="stat">
        <div class="icon">📈</div>
        <div class="stat-label">Pass Rate</div>
        <div class="stat-value">PASS_RATE%</div>
      </div>
    </div>

    CRASHES_SECTION

    LOGCAT_SECTION

    BACKEND_SECTION

    <footer>
      <p>Generated by KeepEat E2E test automation</p>
    </footer>
  </div>
</body>
</html>
HTMLEOF

# Calculate pass rate
PASS_RATE=0
if [ $TOTAL -gt 0 ]; then
  PASS_RATE=$((PASSED * 100 / TOTAL))
fi

# Replace placeholders
sed -i "s/TIMESTAMP_PLACEHOLDER/$(date)/g" "$OUTPUT_FILE"
sed -i "s/PASSED_COUNT/$PASSED/g" "$OUTPUT_FILE"
sed -i "s/FAILED_COUNT/$FAILED/g" "$OUTPUT_FILE"
sed -i "s/TOTAL_COUNT/$TOTAL/g" "$OUTPUT_FILE"
sed -i "s/PASS_RATE/$PASS_RATE/g" "$OUTPUT_FILE"

# Add crashes section if exists
if [ -n "$CRASHES_CONTENT" ]; then
  CRASHES_HTML="<div class=\"section\"><h2>🔥 React Native Crashes</h2><div class=\"log-content\">$CRASHES_CONTENT</div></div>"
else
  CRASHES_HTML="<div class=\"section\"><h2>🔥 React Native Crashes</h2><p style=\"color: #28a745;\">✓ No crashes detected</p></div>"
fi
sed -i "s|CRASHES_SECTION|$CRASHES_HTML|g" "$OUTPUT_FILE"

# Add logcat section if exists
if [ -n "$LOGCAT_CONTENT" ]; then
  LOGCAT_HTML="<div class=\"section\"><h2>📋 Logcat (Last 500 lines)</h2><div class=\"log-content\">$LOGCAT_CONTENT</div></div>"
else
  LOGCAT_HTML="<div class=\"section\"><h2>📋 Logcat</h2><p style=\"color: #999;\">No logcat available</p></div>"
fi
sed -i "s|LOGCAT_SECTION|$LOGCAT_HTML|g" "$OUTPUT_FILE"

# Add backend section if exists
if [ -n "$BACKEND_LOG" ]; then
  BACKEND_HTML="<div class=\"section\"><h2>⚙️ Backend Logs (Last 200 lines)</h2><div class=\"log-content\">$BACKEND_LOG</div></div>"
else
  BACKEND_HTML=""
fi
sed -i "s|BACKEND_SECTION|$BACKEND_HTML|g" "$OUTPUT_FILE"

echo -e "${GREEN}✅ Report generated: $OUTPUT_FILE${NC}"
echo -e "   📊 Results: ${GREEN}$PASSED passed${NC}, ${RED}$FAILED failed${NC}, ${YELLOW}$PASS_RATE% pass rate${NC}"
